"""create admin table

Revision ID: 39cf1465794f
Revises: dbf1043f4426
Create Date: 2025-03-05 15:52:18.662420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39cf1465794f'
down_revision: Union[str, None] = 'dbf1043f4426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_full_name', sa.String(length=30), nullable=False),
    sa.Column('admin_phone', sa.String(length=10), nullable=False),
    sa.Column('admin_email', sa.String(length=250), nullable=False),
    sa.Column('admin_hashed_password', sa.String(), nullable=False),
    sa.Column('admin_created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
