"""add student image and face ID

Revision ID: a70df6c7823c
Revises: 39cf1465794f
Create Date: 2025-03-06 11:06:01.008602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70df6c7823c'
down_revision: Union[str, None] = '39cf1465794f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_image', sa.String(), nullable=False))
    op.add_column('students', sa.Column('student_face_id', sa.JSON(), nullable=True))
    op.add_column('students', sa.Column('student_face_id_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'student_face_id_status')
    op.drop_column('students', 'student_face_id')
    op.drop_column('students', 'student_image')
    # ### end Alembic commands ###
