"""fix hashed mpin length

Revision ID: dbf1043f4426
Revises: 5d5e3002b225
Create Date: 2025-03-05 14:55:55.144875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf1043f4426'
down_revision: Union[str, None] = '5d5e3002b225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffs', 'staff_hashed_mpin',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffs', 'staff_hashed_mpin',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
